[build]
target = "./index.html"

[watch]
watch = ["./src", "./index.html", "./styles.css", "./public", "./Cargo.toml", "./Cargo.lock"]
ignore = ["./src-tauri", "./packaging", "./target", "./dist"]

[serve]
port = 1420
open = false
